line-length = 120

[lint]
ignore = [
    "E741", # Ambiguous variable names, false positive on I for identity matrix
    "B905", # `zip()` without an explicit `strict=` parameter
    "TRY003", # Avoid specifying long messages outside the exception class
]

select = [
    "F", # pyflakes
    "E", # pycodestyle Errors
    "W", # pycodestyle Warnings
    "I", # isort

    "B", # flake8-Bugbear
    "C4",  # flake8-comprehensions
    "FBT", # flake8-boolean-trap
    "SLF",  # flake8-self
    "TID", # flake8-tidy-imports
    "TRY", # tryceratops
    "UP",  # pyupgrade
]
