line-length = 120

[lint]
ignore = [
    "E741" # Ambiguous variable names, false positive on I for identity matrix
]

select = [
    "F", # pyflakes
    "E", # pycodestyle Errors
    "W", # pycodestyle Warnings
    "I", # isort
    "TID", # flake8-tidy-imports
]
