line-length = 120

[lint]
ignore = [
    "E741", # Ambiguous variable names, false positive on I for identity matrix
    "B905", # `zip()` without an explicit `strict=` parameter
]

select = [
    "F", # pyflakes
    "E", # pycodestyle Errors
    "W", # pycodestyle Warnings
    "I", # isort
    "B", # flake8-Bugbear
    "TID", # flake8-tidy-imports
]
