name: Code Style - Jupyter
on:
  pull_request:
    paths:
      - '**.ipynb'
  push:
    branches:
      - main
    paths:
      - '**.ipynb'
  workflow_dispatch:
jobs:
  check-notebooks:
    name: Clean Juypter notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check notebooks are stripped
        uses: kynan/nbstripout@d4149fd617c702ea9e0ef9e6776a8296c979e9cb
        with:
          paths: '**/*.ipynb'
